# Generated by Django 4.2.6 on 2023-10-16 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccountManager',
        ),
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
            ],
        ),
    ]
