# Generated by Django 4.2.6 on 2023-10-21 15:06

from django.db import migrations, models
import profiles.utils


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_useraccountmanager_alter_useraccount_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to=profiles.utils.profile_avatar_dir_path),
        ),
    ]
