# Generated by Django 4.2.5 on 2023-10-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descripsion',
            new_name='description',
        ),
    ]
