# Generated by Django 4.2.5 on 2023-10-07 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_rename_descripsion_recipe_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='RecipeLike',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(blank=True, to='recipes.recipecategory'),
        ),
    ]
