# Generated by Django 4.2.6 on 2023-10-21 15:06

from django.db import migrations, models
import recipes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_like_recipelike_remove_recipe_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(upload_to=recipes.utils.recipe_picture_dir_path),
        ),
    ]
